/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class filip_uncanin_shoppinglist_JNIexample */

#ifndef _Included_filip_uncanin_shoppinglist_JNIexample
#define _Included_filip_uncanin_shoppinglist_JNIexample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     filip_uncanin_shoppinglist_JNIexample
 * Method:    check
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_filip_uncanin_shoppinglist_JNIexample_check
        (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
